# Generated by Django 4.2.21 on 2025-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='operational_location',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='primary_activity',
        ),
        migrations.AddField(
            model_name='company',
            name='operational_location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='primary_activity',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
